termux/termux-app

app/src/main/java/com/termux/app/ExtraKeysView.java

On Android 5 ExtraKeysView shows empty (though can be swiped for TextView).
This is fixed by explicitly specifying alignment as GridLayout.FILL
I have figured out that this was fixed in Android 6 in commit
https://android.googlesource.com/platform/frameworks/base/+/6dafd87fb4174447018b044bc67818d54fab57d8%5E%21/#F0
which set default alignment to FILL if weight is nonzero

Make ExtraKeysView work on Android 5

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java
terminal-emulator/src/test/java/com/termux/terminal/ControlSequenceIntroducerTest.java

When the number of parameters in a CSI control code exceeds the size of
the mArgs array, the code may attempt to read past the end of the array,
resulting in a force close of the app.
Stop the index from moving past the last element of the mArgs array.

Fix FC from too many control code parameters

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java
terminal-emulator/src/test/java/com/termux/terminal/CursorAndScreenTest.java

SGR attributes are stored in three variables: mEffect, mForeColor, and
mBackColor.  Saving/restoring the cursor only preserves mEffect.
Change the cursor save/restore methods to additionally preserve
mForeColor and mBackColor.  This affects both 'explit' saving/restoring
the cursor and switching to/from the alternate screen buffer.

Make cursor save/restore affect color attributes

---

app/src/main/AndroidManifest.xml

A single meta-data entry is enough to make Termux "Multi Window" aware on supported Samsung devices.
Tested and confirmed working on Samsung Note Pro 12.2 running Android 5.1.1.
This addition should not interfere with Android 6+'s split screen feature.
Tested and confirmed split screen functions as normal on a Nexus 6 running Android 7.0.
This addition should go unnoticed on non-Smasung Android 5 devices.
Tested and confirmed no functionality visible on Nexus 5 running Android 5.1.

Add Multi Window support for Samsung devices

---

app/src/main/AndroidManifest.xml

Verified with Developer Preview 3 image on Raspberry Pi 3.
About why "home activity" is required, please check the link:
https://developer.android.com/things/sdk/index.html

[Android-things] Launch TermuxActivity automatically on boot

---

app/src/main/java/com/termux/app/TermuxHelpActivity.java

HELP page wiki changed to https://wiki.termux.com/wiki/Main_Page as it now has more info than http://termux.com/help.html

replace help url with wiki url

---

app/src/main/java/com/termux/app/TermuxService.java

since we're a foreground service, in oreo we already get a higher
priority; see
https://developer.android.com/reference/android/app/NotificationManager.html#IMPORTANCE_MIN

set default notification priority to low

---

app/src/main/res/drawable/ic_service_notification.xml

Icons used in notifications/status bar are monochrome and should use only white color and transparency. It is displayed fine on Android emulators but it's shown in black on Samsung Galaxy S7 running Android 7.0.
After the change, status bar icon is white and the small icon in notification still uses the black color set via setColor(). Termux doesn't support devices running Android older than 5.0 but using white color in vector drawables would be also necessary to generate proper (white) bitmap icons.

Fix notification icon color

---

terminal-view/src/main/java/com/termux/view/TerminalRenderer.java

I want to use the renderer with a custom canvas without having to render to an Android View which requires a context and all sorts of stuff.
Can't currently do that because the renderer is package-private.
The goal is to be able to render this onto a texture in Unity so that people can easily make stuff with termux in VR.

Make TerminalRenderer public

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java

Termux will now properly send `\r` to the terminal instead of `\n` when pasting multiline strings.
This fixes `cat` not repeating back lines and `nano` accidentally justifying text (because `\n` maps to `^J`), as well as other potential issues.
This matches the behavior of other terminals, such as iTerm2 which explicitly does it here:
https://github.com/gnachman/iTerm2/blob/f8a5930/sources/iTermPasteHelper.m#L113

Replace \n with \r when pasting (Fixes #678)

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalRow.java

Added fast path for TerminalRow.setChar for case where theres 1-to-1 mapping between characters and columns (that is no UTF-16 surrogate pairs and characters with width != 1)
Trying to fix termux/termux-app#603, please test @evg-zhabotinsky
In my tests this highly improved performance of `cat 500KBfile.txt` test.
Still slower than Android Terminal Emulator, but difference is now much smaller and seems to be matter of redraw throttling, without redrawing Termux is now faster (For test commented out line in [Termux](https://github.com/termux/termux-app/blob/9f36ed06b8e2c3b5e5918444e0c37699e21a7196/terminal-view/src/main/java/com/termux/view/TerminalView.java#L386) and [Android Terminal Emulator](https://github.com/jackpal/Android-Terminal-Emulator/blob/987e4eb56bb7bcb387a187ab78437111d327c98 …

Add fast path for TerminalRow.setChar

---

app/src/main/java/com/termux/app/BackgroundJob.java

PS1 is not supposed to be an env var and should be shell-specific.
We will set it appropriately with the init files of the shells.
Companion commit: https://github.com/termux/termux-packages/pull/2554

Stop exporting PS1

---

terminal-view/src/main/java/com/termux/view/TerminalView.java

Terminal view as implemented in the termux app is a view resembling terminal windows known from computers. It's designed to be efficient however for me and other people who are using accessibility services such as Google Talkback to access their android devices it's not very usable. By adding contentDescription property to the view dynamically as it repaints, we can get at least very basic accessibility support.
When using termux on Android with Talkback running it is possible to review currently visible text on the screen by characters, by words and by lines.
It is possible to use two finger scrolling (android built-in feature) to scroll the view and access other parts of the text.
I'm using this for a few months already and I have got some friends interested in this functionality so I'm …

Basic accessibility support for the terminal view

---

app/src/main/java/com/termux/app/TermuxInstaller.java

Prevents possible data loss when user replaced directory '~/storage' with
a symlink. Issue: https://github.com/termux/termux-app/issues/738

deleteFolder(): check if passed argument is a symlink

---

terminal-view/src/main/java/com/termux/view/TerminalView.java

- in onKeyDown() ignore keys when the Fn key is pressed
- in onKeyDown() return false when the key is not handled.
The above two changes fix the handling of Fn-key combo's on devices with
a physical keyboard, allowing the android system defined fallbacks from
`/system/usr/keychars/Generic.kcm` to be properly handled.
Fixes #731.
Original diagnosis and fix by Konehaltia.

Alternative patch to fix fn-up fn-down pgup/pgdown

---

app/src/main/java/com/termux/app/TermuxActivity.java

An attempt to deal with these issues:
* https://github.com/termux/termux-app/issues/627
* https://github.com/termux/termux-app/issues/56
This PR makes sessions be closed automatically without pressing enter. However to close last session user will have to press enter - this allows to start a 'fallback' session so user can fix things if normal session can't be started.

close sessions without waiting for user input except the last one

---

app/src/main/res/layout/drawer_layout.xml

Commit f0eeb47 introduced configurable extra keys and thus changed the
height of the viewpager to be multipled by the number of rows of extra
keys. However, the extra keys had two rows at the time, so the initial
height should have been changed to half of what it was now that it is
multiplied. This was not done, so the viewpager was twice the height it
should be after that change.

Reduce the height of viewpager/ExtraKeysView to previous height

---

app/src/main/java/com/termux/app/TermuxActivity.java

This PR should prevent erasing of $TMPDIR on start by Termux:Boot or Termux:Widget. On normal application start erasing of /tmp will be performed anyway.

sessions: do not clear TMPDIR if application was not started

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/termux/app/TermuxActivity.java
app/src/main/java/com/termux/app/TermuxFailsafeActivity.java
app/src/main/res/values/strings.xml

Enables additional launcher icon that causes to be a failsafe session to be started instead of default.
This PR also makes session auto-closeable on exit coded *0* and *130*. Any other exit codes should be handled by user on it's own in order to avoid messages about "Press enter".
Old "failsafe" session button left untouched since it may be useful in some cases to start system shell instead of Termux's one.

sessions: failsafe session is now accessible via separate launcher icon

---

app/src/main/java/com/termux/app/BackgroundJob.java

Export `ANDROID_RUNTIME_ROOT` environment variable if it's present
With that, `am` and `apksigner` work on Android Q

Make am work on Android Q

---

app/src/main/java/com/termux/app/TermuxService.java

As the notification icon and text is set to black, ROMs like Samsung OneUI and themes that change notifications to have a dark background will have visibility issues with Termux notifications. This commit sets a neutral color which will be visible on both white and dark backgrounds.

Tweak notification icon color to make it work with dark notifcations

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/termux/app/TermuxActivity.java
app/src/main/java/com/termux/app/TermuxService.java

* Intent category "default" is not needed after dropping failsafe icon.
* Also move the routines to clear /tmp dir to TermuxService.onDestroy().

Remove intent category "default" from manifest

---

app/src/main/java/com/termux/app/BackgroundJob.java

Required on at least Android 5. Otherwise utilities that use dalvikvm may fail.
Issue happens on Nexus 7 with official 5.0/5.1 firmware and possibly other AOSP ROMs.

set BOOTCLASSPATH environment variable

---

app/src/main/java/com/termux/app/BackgroundJob.java

Since Android Q Beta 2 ANDROID_TZDATA_ROOT is required
in addition to ANDROID_RUNTIME_ROOT in order to run
`am` and `dalvikvm`

Also export ANDROID_TZDATA_ROOT

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/termux/app/TermuxService.java

Fixes #377 by whitelisting termux when the user clicks on the wakelock button for the first time.
Even if the [android docs](https://developer.android.com/training/monitoring-device-state/doze-standby.html) say a foreground service is enough to prevent suspension, on my devices running CLI services stop sending UDP/TCP packets and get suspended if the app is reduced or the device is locked.
This is especially noticeable when running a simple `time ping 192.168.1.1`; on resume, the ICMP sequence number is way lower than the number of elapsed seconds, indicating a suspension of the process.
Anyway, I encountered this issue on my devices and noticed that manual whitelisting fixed it, thought I could contribute with an automated fix.

Ignore battery optimization settings to prevent suspension

---

app/src/main/java/com/termux/app/BellUtil.java
app/src/main/java/com/termux/app/TermuxActivity.java

This class is used to represent BellUtil.  This method named 'with' is to return the singleton of BellUtil instance. Thus, the method name 'getInstance' is more intuitive than 'with'.

Change method name 'with' to 'getInstance'

---

app/src/main/java/com/termux/app/ExtraKeysView.java

Will prevent haptic feedback when it is disabled in Android settings or "Do not disturb" mode active.

extra keys: follow DnD mode and haptic feedback Android settings

---

app/src/main/AndroidManifest.xml

Required by some Android TV devices.
https://github.com/termux/termux-packages/issues/1761#issuecomment-540141763

Add permission ACCESS_NETWORK_STATE

---

app/src/main/java/com/termux/app/TermuxActivity.java
app/src/main/java/com/termux/app/TermuxPreferences.java
app/src/main/res/drawable/current_session.xml
app/src/main/res/drawable/current_session_black.xml
app/src/main/res/drawable/selected_session_background_black.xml
app/src/main/res/drawable/session_ripple.xml
app/src/main/res/drawable/session_ripple_black.xml
app/src/main/res/layout/drawer_layout.xml
app/src/main/res/values/styles.xml

I've made sidebar black instead of white and made app use dark android theme for consistency in Alert Dialogs etc. No more being blinded by UI elements at night
fixes https://github.com/termux/termux-app/issues/789
fixes https://github.com/termux/termux-app/issues/781

Unified UI colors across the app. 

---

.gitignore
app/build.gradle
app/src/main/cpp/Android.mk
app/src/main/cpp/termux-bootstrap-zip.S
app/src/main/cpp/termux-bootstrap.c
app/src/main/java/com/termux/app/TermuxInstaller.java

This is an experiment with including the bootstrap zip as a shared library.
The gradle build now downloads the bootstrap of a specified version from bintray.
- Why include the bootstrap zip in the app?
- To save several terabytes of monthly bandwidth on the server, and instead rely on Google to provide a speedy download of bootstrap files.
- To allow offline installation.
- To avoid surprising users with data traffic on first use.
- Why as a shared library?
- To make the app splitting work on Google Play. Termux is uploaded to the Play store as an Android App Bundle, and Google generates optimized apps for devices, so that e.g. only aarch64 devices gets the aarch64 bootstrap. See https://developer.android.com/studio/projects/dynamic-delivery. F-Droid can also do the corresponding thing …

Include bootstrap zip as shared library

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/backupscheme.xml

Why:
* During backup process Termux is being killed in most cases.
* Backup data is limited to 25 MB.
* Backup may not be performed/updated in certain cases.
One of the reasons why issue https://github.com/termux/termux-app/issues/122 happens.

Disable backups by Google services

---

app/src/main/java/com/termux/app/ExtraKeysView.java

Extra keys shouldn't perform any action if button click was cancelled.
Fixes: https://github.com/termux/termux-app/issues/905.
Additionally:
* Disable manual handling of DnD for API 28 and higher (Google simplified it and seems there no way to detect total silence mode). Maybe for higher SDK versions we even do not need to handle it manually, but I don't have device to verify this.

extra keys: handle actions UP & CANCEL separately

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java

Fixes utility 'reset' not being able to clear scrollback buffer.

terminal emulator: clear scrollback buffer when resetting to initial state

---

app/src/main/java/com/termux/app/BackgroundJob.java
app/src/main/java/com/termux/app/TermuxService.java

I've added an optional final argument to the BackgroundJob constructor for a `PendingIntent` that it will respond to with the results of the commands that it has run. (A "result" bundle containing stdout, stderr, and the process exit status)
I've also added a `"pendingIntent"` extra that will be pulled from `service_execute` requests that can hold these new PendingIntents, so Termux can respond to things that can invoke these intents with the resulting command's output.
The immediate practicality of this is that it will allow things like [this issue in termux-tasker](https://github.com/termux/termux-tasker/issues/21) to be solved.

BackgroundJob command result responses

---

app/src/main/java/com/termux/app/TermuxPreferences.java
app/src/main/java/com/termux/app/TermuxViewClient.java

Adds the option to disable volume button virtual CTRL and FN emulation. Use volume-keys=volume within termux.properties to enable this behaviour.
This should resolve #119.
Tested on Android 8.0.0.

Allow the user to disable virtual key emulation.

---

app/src/main/java/com/termux/filepicker/TermuxDocumentsProvider.java

Fix #1424 and #1350.
Also fixes folders not deletable & corrected logic for deletable flag.

Fixes for DocumentsProvider

---

.github/workflows/gradle-wrapper-validation.yml

Here you have the full story https://github.com/gradle/wrapper-validation-action
In short: it fails if unknown Gradle Wrapper JAR files is found.

Verify Gradle

---

app/src/main/java/com/termux/app/TermuxPreferences.java

Should fix
```
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
```
?

Handle all exceptions when loading termux.properties

---

app/src/main/java/com/termux/app/TermuxPreferences.java

By default it uses the system setting. If use-black-ui is set to either
true or false, that overrides it.
Fixes #1351 properly, fixes #1354

Support auto detection of dark theme

---

terminal-view/src/main/java/com/termux/view/TerminalView.java

When you hold down on a word that starts or ends at the edge of the
screen, the handle will appear outside of the screen. This happens
because the orientation was only switched when the handle is dragged, so
when it is shown it just used the same orientation as it had for the
last selection.
Relates to #334, but not sure if it fixes it completely.
Before:
After:
This is when holding down on the word "Working".

Set orientation of HandleView in show

---

app/src/main/res/drawable/ic_service_notification.xml

This is the launcher icon with a circle around it. I added the circle
because the icon has a transparent background, so it looks a bit weird
with just the >_.

Update notification icon to match launcher icon

---

app/src/main/java/com/termux/app/ExtraKeysInfos.java
app/src/main/java/com/termux/app/ExtraKeysView.java
app/src/main/java/com/termux/app/TermuxActivity.java
app/src/main/java/com/termux/app/TermuxPreferences.java
build.gradle
terminal-view/src/main/java/com/termux/view/TerminalView.java

This adds support for multiple things for the extra keys.
- The popup keys are now configurable
- The style can be configured, e.g. if PGUP should be shown as text or an arrow character etc.
- Modifier keys can now be used with the other keys on the extra keys rows.
- Keys can be mapped to other and multiple actions. This allows you to use whatever text you want on the button for an action, and it also allows you to define macros.
See the commit messages for more details.

Improvements to extra keys

---

app/src/main/java/com/termux/app/TermuxActivity.java
terminal-emulator/src/main/java/com/termux/terminal/TerminalBuffer.java
terminal-emulator/src/test/java/com/termux/terminal/ScreenBufferTest.java

Some terminal applications, like mutt and weechat, prints a newline at
the end of each line even if text is wrapped. This causes urls which are
wrapped to not be selectable in full.
By ignoring newlines when the text fills the entire width of the screen,
those urls can be selected. Many other terminal emulators do this as
well.
A drawback of this is that if a url happens to fill the width of the
screen, the url selection will include the first word of the next line,
but this doesn't happen that often so I think it's an okay tradeoff.
Fixes #313

Join lines that fills the width when selecting urls

---

terminal-view/src/main/java/com/termux/view/TerminalRenderer.java

There is currently a bug where selection rendering is broken if the active cursor shape is anything other than the default solid box. Selected text is normally highlighted by effectively rendering a cursor over all of the characters in the selection region, but if the cursor is a bar, the resulting selection highlight is too narrow to cover the full width of the selection. Similarly, if the cursor is an underline, all of the selected text will be underlined instead of highlighted.
To fix this issue, treat selections different from cursors in the rendering logic and force the renderer to always use the block cursor style for rendering selections. That way, we get correct behavior regardless of what the current cursor shape is.
Example:
Before:
After:

Fix selection rendering with alternate cursor styles

---

terminal-view/src/main/java/com/termux/view/TerminalRenderer.java

Highlighting text in the terminal often makes it hard to read, which can be problematic for users who want to adjust or review selections before copying them. For example, the default theme makes white and green text hard to read on its light gray selection background, and there are plenty of other themes where the choice of text and cursor colors would hinder selection readability.
To fix this issue and make selected text more legible in nearly all combinations of colors, invert selected text instead of highlighting it. This is more common among terminal emulators anyway:
- Invert: xterm, fbcon, kitty, Konsole, Alacritty, Tilix, gnome-terminal (7)
- Highlight: Termux, Terminal.app, iTerm2, Windows Terminal (4)

Invert selected text instead of highlighting

---

app/src/main/java/com/termux/app/RunCommandService.java
app/src/main/java/com/termux/app/TermuxService.java

Fixes `RUN_COMMAND_ARGUMENTS` extra for `RUN_COMMAND_ACTION` intent. Check [here](https://github.com/termux/termux-app/pull/1029#issuecomment-666481152) for details.
Adds `RUN_COMMAND_BACKGROUND` extra for `RUN_COMMAND_ACTION` intent to run termux session in background. Check [here](https://github.com/termux/termux-app/pull/1029#issuecomment-649715644) for details.
Hopefully, this should fix the issues. I haven't tested the code but seems fine on overview since minimal changes are made in java code. Let me know if I should test as well.

Bug fixes and improvements for "RUN_COMMAND_ACTION" intent. Issue #1029.

---

app/build.gradle
gradle.properties
terminal-emulator/build.gradle
terminal-view/build.gradle

move sdk version configs to gradle.properties to avoid modify each build.gradle every time

move sdk version configs to gradle.properties

---

terminal-emulator/src/main/java/com/termux/terminal/WcWidth.java

https://github.com/termux/wcwidth/pull/4
in regards to the synchronization note, if a character appears in the app as 1 wide but in the C function as 2 or vice versa, line editing breaks, especially with `mark-modified-lines`. e.g. currently the hedgehog emoji 🦔 displays as 1 wide but is detected as 2 wide. try editing a line with it halfway through.

update WcWidth.java, add note about c version

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/termux/app/RunCommandService.java

Since `startForeground()` function is not being called, occasionally termux is killed by android with the following exception
```
I/ActivityTaskManager: START u0 {flg=0x10000000 cmp=com.termux/.app.TermuxActivity} from uid 10138
W/ActivityTaskManager: Background activity start [callingPackage: com.termux; callingUid: 10138; isCallingUidForeground: false; isCallingUidPersistentSystemProcess: false; realCallingUid: 10138; isRealCallingUidForeground: false; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: null; isBgStartWhitelisted: false; intent: Intent { flg=0x10000000 cmp=com.termux/.app.TermuxActivity }; callerApp: ProcessRecord{75609ea 14280:com.termux/u0a138}]
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.termux, PID: …
```

Fix RunCommandService crash and foreground issue

---

app/src/main/java/com/termux/app/TermuxActivity.java
app/src/main/res/layout/drawer_layout.xml
app/src/main/res/values/strings.xml
terminal-view/src/main/java/com/termux/view/TerminalView.java

It would help users if they were able to let their password managers enter passwords into terminal sessions for them. While there are legacy solutions for this that already work with Termus (accessibility services and custom IMEs), as of Android Oreo, the preferred method for this usecase is using the system-provided Autofill API.
This commit adds a context menu action that sends a password field Autofill request to the currently registered Autofill service. Triggering the Autofill UI requires an explicit user action (due to `importantForAutofill="no"`) and the context menu action is only shown when Autofill is both supported and enabled.

Add an "Autofill password" context menu action

---

app/src/main/java/com/termux/app/BackgroundJob.java

busybox doesn't use that folder anymore, and is deprecated anyway

don't add $PREFIX/bin/applets to $PATH

---

app/src/main/java/com/termux/filepicker/TermuxDocumentsProvider.java

Credit to @johnmellor for requesting the document provider in the
first place via #79, mentioning this limitation in a comment on
that issue, and creating a commit like this one to address it.

Don't exclude hidden files from document provider (#1220)

---

terminal-view/src/main/java/com/termux/view/TerminalView.java

Should fix (or well, allow user to set a property and thereby fix) https://github.com/termux/termux-app/issues/1333. 
This is a problem in for example emacs when a user uses a hardware keyboard and wants to mark text by pressing ctrl+space. On some devices pressing ctrl + space currently does nothing, but with PR users that want this functionality can add `ctrl-space-workaround=true` to `~/.termux/termux.properties` and then run `termux-reload-settings` to make ctrl+space work as expected. 
Confirmed to work on my phone.

Add workaround property to fix ctrl+space on devices where this does not work

---

app/src/main/java/com/termux/app/FullScreenWorkAround.java
app/src/main/java/com/termux/app/TermuxActivity.java
app/src/main/java/com/termux/app/TermuxPreferences.java

Addresses: https://github.com/termux/termux-app/issues/507
Just setting full screen flag causes issue w/ ExtraKeysView:
`FullScreenWorkAround` class was added to help fix issues across various devices so that ExtraKeysView displays properly:
Example of `termux.properties` config for full screen w/ work-around:
~~`fullscreen-workaround-method = 1` tested w/ Pixel (Emulator)
`fullscreen-workaround-method = 2` tested w/ Samsung S7 and OnePlus 6T
`fullscreen-workaround-method = 3` tested w/ Sony Xperia XZ~~
Some trial and error may be needed for your device.. Another workaround may be needed if the above do not work.
Feedback and testing appreciated!

Implement full screen and add FullScreenWorkAround to fix ExtraKeysView

---

app/build.gradle

Currently we build a single APK which handles the four supported ABIs.
Therefore each user, downloads 50-75% more than they need - adding
towards both client/server-side network as well as device storage.
Use a split APK approach - it costs nothing from build and server-side
storage POV.
Note: We're removing ndk:abiFilters - they're incompatible/superseded by
the splits:abi:include list.
Signed-off-by: Emil Velikov <emil.l.velikov@gmail.com>

app: enable split apk builds

---

app/src/main/java/com/termux/app/ExtraKeysView.java

Improve ExtraKeysView to handle modifier popups (ALT, CTRL and FN) as described in issue [#1880](https://github.com/termux/termux-app/issues/1880) by [haarp](https://github.com/haarp).
Add the possibility to have multiple buttons for the same modifier key and synchronize their state.

ExtraKeysView: Handle multiple and popup SpecialButtons

---

terminal-emulator/src/main/java/com/termux/terminal/KeyHandler.java
terminal-emulator/src/test/java/com/termux/terminal/KeyHandlerTest.java
terminal-view/src/main/java/com/termux/view/TerminalView.java

Implement numpad arrows/home/end/pgup/pgdn/ins/del when num lock is off

---

app/src/main/java/com/termux/app/TermuxActivity.java
app/src/main/java/com/termux/app/terminal/TermuxTerminalViewClient.java

1. If `soft-keyboard-toggle-behaviour=enable/disable` was set, then pressing keyboard toggle wouldn't show the keyboard after switching back from another app if keyboard was previously disabled by user.
2. If switching back from another app, like when opening url with context menu "Select URL" long press and returning to termux with back button, then soft keyboard wouldn't automatically open like it does on app startup.
Fixes #2111, Fixes #2112
@trygveaa Here it is, kindly test. Thanks.

Fix issue where soft keyboard would not show in some cases

---

README.md

I guess discord is used by most people, and basically some people don't use gitter
i might add this badge to other repos as well

Add Discord badge link

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalColorScheme.java
terminal-view/src/main/java/com/termux/view/TerminalRenderer.java

Issue: https://github.com/termux/termux-app/issues/219
Before
After
***
Another commit changes default cursor color to white, which in my opinion is better suitable for default color scheme.
When using bar cursor style, it has worse visibility if colored in grey:

terminal: invert text color under block cursor

---

termux-shared/src/main/AndroidManifest.xml

./gradlew lint complains about vibrations being used in termux-shared/src/main/java/com/termux/shared/terminal/io/BellHandler.java without the permission being declared:
```
/home/grimler/projects/termux/termux-app/termux-shared/src/main/java/com/termux/shared/terminal/io/BellHandler.java:45: Error: Missing permissions required by Vibrator.vibrate: android.permission.VIBRATE [MissingPermission]
vibrator.vibrate(VibrationEffect.createOneShot(DURATION, VibrationEffect.DEFAULT_AMPLITUDE));
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/grimler/projects/termux/termux-app/termux-shared/src/main/java/com/termux/shared/terminal/io/BellHandler.java:47: Error: Missing permissions required by Vibrator.vibrate: android.permission.VIBRATE …
```

termux-shared: add android.permission.VIBRATE to manifest

---

app/src/main/java/com/termux/app/RunCommandService.java
app/src/main/java/com/termux/app/TermuxService.java
app/src/main/java/com/termux/app/terminal/TermuxTerminalSessionClient.java
app/src/main/res/values/strings.xml
termux-shared/src/main/java/com/termux/shared/shell/command/ExecutionCommand.java
termux-shared/src/main/java/com/termux/shared/termux/TermuxConstants.java
termux-shared/src/main/java/com/termux/shared/termux/shell/command/runner/terminal/TermuxSession.java

This is done via addition of the `com.termux.RUN_COMMAND_SESSION_CREATE_MODE` extra, which currently supports two values.
- `always` to always create a new session every time.
- `no-session-with-name` to create a new session only if no existing session exits with the same terminal session name.
The terminal session name will equal executable basename by default and dashes `-` in the basename will no longer be replaced with spaces when session name as done previously. The `com.termux.RUN_COMMAND_SESSION_NAME` extra can be used to set custom session name. 
Usage:
You can use this with `Termux:Tasker` or `Termux:Widget`.
For example for `Termux:Widget`
- Create a wrapper script at `~/.shortcuts/tasks/my-script.sh` with following contents under `tasks` directory so that it runs in background …

Add support to switch to existing session instead of creating duplicate session for `RUN_COMMAND` intent

---

termux-shared/src/main/java/com/termux/shared/termux/settings/preferences/TermuxAPIAppSharedPreferences.java
termux-shared/src/main/java/com/termux/shared/termux/settings/preferences/TermuxPreferenceConstants.java

For use with https://github.com/termux/termux-api/pull/556 and https://github.com/termux/termux-api-package/pull/161
See https://github.com/termux/termux-api/issues/550 and https://github.com/termux/termux-api/issues/246

Add LastPendingIntentRequestCode support to TermuxAPIAppSharedPreferences

---

terminal-emulator/src/main/java/com/termux/terminal/KeyHandler.java

Don't know why didn't anyone else report this. It's a pretty common keybinding for working with tabs on most applications. The fix is unsurprisingly simple.

feat(KeyHandler): respect modifiers with PgUp and PgDn

---

.github/workflows/attach_debug_apks_to_release.yml

As discussed in https://app.element.io/#/room/#termux_dev:gitter.im

ci(attach_debug_apks_to_release): delete release on failure to build/upload

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalRow.java
terminal-emulator/src/main/java/com/termux/terminal/WcWidth.java

This prevents the crash in #3839, but not by enough to call it done. Termux gets stuck on the very bad line and is responsive, but laggy enough to trigger ANRs. It's possible to ^C in this state and get your terminal back with no apparent damage.

Fixed: Widen TerminalRow's index so very long lines don't overflow it.

---

README.md

The current information is generating a lot of confusion, hopefully this updated one feels ok?

Changed: Update information regarding Google Play in README

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java
terminal-emulator/src/test/java/com/termux/terminal/ScrollRegionTest.java
terminal-emulator/src/test/java/com/termux/terminal/TerminalTestCase.java

Fixes https://github.com/termux/termux-packages/issues/12556
Issue was also reported here:
https://www.reddit.com/r/termux/comments/1df1dii/how_can_i_fix_this_annoying_screenfilling_thing/

Fixed: Use current bg color when scrolling with horizontal margins

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java
terminal-emulator/src/test/java/com/termux/terminal/TerminalTest.java

Currently the Termux terminal emulator prints `HI` in red with:
```sh
printf "\e[31;m HI \e[0m"
```
This is not how other terminals (tested on xterm, gnome-terminal, alacritty and the mac built in terminal) handle it, since they parse `\e[31;m` as `\e[31;0m`, where the `0` resets the colors.
This change aligns with other terminals, as well as improves performance by avoiding allocating a new `int[]` array for each byte processed by `parseArg()`, and most importantly simplifies things by removing the `mIsCSIStart` and `mLastCSIArg` state, preparing for soon supporting `:` separated sub parameters such as used in
https://sw.kovidgoyal.net/kitty/underlines/

Fixed: Improve handling of empty ';' SGR sequences

---

terminal-view/src/main/java/com/termux/view/TerminalView.java

In other terminals, such as gnome-terminal, Shift-PgUp and Shift-PgDn
scroll the screen by a full page, rather than a single line. Adjust
termux to match.

Make Shift-PgUp and Shift-PgDn scroll by pages rather than lines

---

app/src/main/java/com/termux/app/TermuxActivity.java
app/src/main/res/layout/activity_termux.xml
app/src/main/res/values/strings.xml
terminal-view/src/main/java/com/termux/view/TerminalView.java

- The AutoFill type and hints are no longer hardcoded in `TerminalView` class and `TermuxActivity` layout xml. They are dynamically set to required values before making a manual AutoFill request and reverted back afterwards to default values. The hardcoded value `AUTOFILL_TYPE_TEXT` returned by `getAutofillType()` was causing the AutoFill UI to show on Activity starts, this will return `AUTOFILL_TYPE_NONE` by default now so that AutoFill UI isn't shown automatically.
- The AutoFill importance is no longer hardcoded in `TermuxActivity` layout xml and is returned by `TerminalView` class itself by `getImportantForAutofill()`.
- The AutoFill function in `TermuxActivity` for making a manual AutoFill request is moved to `TerminalView` class. This and moving of hardcoded values to `TerminalView` …

Do not show AutoFill UI on Termux start and add support for usernames

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java
terminal-emulator/src/test/java/com/termux/terminal/ApcTest.java

Parse Application Program-Control (APC) terminal escape sequences - sequences starting with `ESC _` and ending with `ESC \` (String Terminator, ST).
Reference: https://www.xfree86.org/current/ctlseqs.html
This is a first small step toward supporting [Kitty terminal graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/) as it uses APC sequences, and fixes e.g. characters being incorrectly shown on screen when returning from `yazi`(see below video), since that program [probes for Kitty support](https://github.com/sxyazi/yazi/blob/0cdaff98d0b3723caff63eebf1974e7907a43a2c/yazi-adapter/src/emulator.rs#L129) by writing an APC sequence that is either handled (by terminals supporting the kitty graphics protocol) or should be ignored (by terminals not supporting it, which we here …

Fixed: Parse (but ignore for now) terminal APC sequences

---

terminal-view/src/main/java/com/termux/view/TerminalView.java

Currently the view is still marked as not important even after requesting an autofill.

fix: Mark view as important for AutoFill after requesting an AutoFill

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java
terminal-emulator/src/main/java/com/termux/terminal/TerminalSession.java
terminal-emulator/src/test/java/com/termux/terminal/ControlSequenceIntroducerTest.java
terminal-emulator/src/test/java/com/termux/terminal/HistoryTest.java
terminal-emulator/src/test/java/com/termux/terminal/ResizeTest.java
terminal-emulator/src/test/java/com/termux/terminal/TerminalTest.java
terminal-emulator/src/test/java/com/termux/terminal/TerminalTestCase.java

Implement the following CSI escape sequences from https://invisible-island.net/xterm/ctlseqs/ctlseqs.html:
> CSI Ps ; Ps ; Ps t
> [..]
>    Ps = 1 4  ⇒  Report xterm text area size in pixels.
>    Result is CSI  4 ;  height ;  width t
> [..]
>    Ps = 1 6  ⇒  Report xterm character cell size in pixels.
>    Result is CSI  6 ;  height ;  width t
Extracted from changes in https://github.com/termux/termux-app/pull/2973 by @MatanZ and adopted to play well with the just merged #3098 (.ws_xpixel and .ws_ypixel values in winsize).

Added: Terminal CSI reporting of window and cell pixel size

---

terminal-view/src/main/java/com/termux/view/TerminalRenderer.java

drawText does (very) basic BiDi, which causes inconsistent behaviour. This change ensures everything is LtR.
This fixes #1256 (and somewhat #296).

Use Canvas.drawTextRun instead of drawText

---

app/src/main/java/com/termux/app/TermuxOpenReceiver.java

This fixes apps that rely on [getType](https://developer.android.com/reference/android/content/ContentResolver#getType(android.net.Uri)), for example [WallpaperPicker2](https://cs.android.com/android/platform/superproject/+/master:packages/apps/WallpaperPicker2/src/com/android/wallpaper/asset/ContentUriAsset.java;l=158;bpv=1;bpt=1?q=isJpeg).

Basic MIME type recognition in ContentProvider

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java
terminal-emulator/src/test/java/com/termux/terminal/ScrollRegionTest.java

SD sequence (`${CSI}${N}T`) was scrolling the whole width
of the terminal instead of just between the margins.
RI sequence (`${ESC}M`, move cursor up 1 line) was doing the same. Fixed that.
Fixes #2576 where in tmux scrolling one of several
side-by-side panels down resulted in all visually scrolling.

Fixed: Make ScrollDown escape respect margins

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java
terminal-emulator/src/test/java/com/termux/terminal/ControlSequenceIntroducerTest.java
terminal-emulator/src/test/java/com/termux/terminal/TerminalTest.java

It seems that more and more terminal emulators and terminal programs supports colon (`:`) as well as semicolon (`;`) to specify colors:
```sh
red=255 green=100 blue=0 
printf "\x1b[38;2;${red};${green};${blue}m TRUECOLOR\n" # Semicolon separated, works in Termux
printf "\x1b[38:2:${red}:${green}:${blue}m TRUECOLOR\n" # Colon separated, implemented in this PR
```
See https://github.com/termstandard/colors?tab=readme-ov-file#truecolor-support-in-output-devices, where it can be seen that multiple terminal emulators also support using a colon as delimiter nowadays:
- [alacritty](https://github.com/jwilm/alacritty) [delimiter: colon, semicolon] - written in Rust
- [iTerm2](https://iterm2.com/) [delimiter: colon, semicolon] - since v3 version
- [kitty](https://github.com/kovidgoyal/kitty) …

Fixed: Implement colon separated CSI parameters

---

app/src/test/java/com/termux/app/api/file/FileReceiverActivityTest.java

Added to FileReceiverActivityTest empty & null strings for invalidUrls to cover corner cases

Changed: Updated FileReceiverActivityTest to include empty & null strings for invalidUrls to cover corner cases

---

terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java

Standard ECMA-48: Control Functions for Coded Character Sets specifies
the format of CSI commands.  Wikipedia has a concise description:
https://en.wikipedia.org/wiki/ANSI_escape_code#Control_Sequence_Introducer_commands
Do this for at least for sequences like "CSI = 5 u" that
contain non-numeric parameter bytes.
This fixes a problem with fish shell 4.0.0 which (for better or worse)
uses that sequence.
This patch introduces a slight inconsistency: for the above example,
"unknownSequence('u')" will be called.  The resulting log message may
be confusing, because we *do* support "CSI u". We should fix this to
log the entire unknown sequence. I can try doing that.
In future we should also fully consume all other unknown CSI commands.
A contrived example would be "CSI ! ! a".  If desired, I'm …

Fixed: fully consume unknown CSI sequences containing non-numeric parameter byte
