termux/termux-app

gradle/wrapper/gradle-wrapper.properties, gradlew.bat
This also adds the missing `gradlew.bat` script.
=> Update Gradle wrapper to 3.2

app/src/main/java/com/termux/app/ExtraKeysView.java, app/src/main/res/layout/drawer_layout.xml, terminal-view/src/main/java/com/termux/view/TerminalView.java
Just like JuiceSSH, more convenient. For example, long press `arrow key` to continuous input arrows, slip up `/` key to input `\`. Also fix #571 or #12 .
=> add some func keys

app/src/main/java/com/termux/app/TermuxInstaller.java
Also see #578 for a merging alternative WIP
=>  Fix for #572 using recursive delete

app/src/main/java/com/termux/app/TermuxInstaller.java
Should fix https://github.com/termux/termux-app/issues/735
=> deleteFolder(): don't treat symlinks as directory

app/src/main/java/com/termux/app/ExtraKeysView.java
Sadly I don't have the real phone to test for these issues(#739, #741), not sure if they are truely fixed.
=> fix #739 and #741.

app/src/main/java/com/termux/app/TermuxActivity.java, app/src/main/java/com/termux/app/TermuxService.java
Fix for https://github.com/termux/termux-app/issues/636. Clean /tmp directory on application start.
=> clean /tmp directory on cold start

app/src/main/res/layout/drawer_layout.xml
Should fix https://github.com/termux/termux-app/issues/516
I guess padding of 3dp should be enough.
=> add some padding for TerminalView

.travis.yml
This bumps build-tools from 27.0.3 to 28.0.2.
=> Update travis to android 28

app/src/main/java/com/termux/app/TermuxPreferences.java
When having an malformed json input in the extra-keys property, the termux-app crashes later with an NullpointerException due to an uninitialized mExtraKeys variable.
This fix improves the parsing of the properties file. In case of an invalid "extra-keys" property, the variable will be initialized with length 0.
=> Fix Termux crash on malformed config file

app/src/main/res/layout/extra_keys_right.xml
Should fix https://github.com/termux/termux-app/issues/1019.
=> native text input: make text selection visible

app/src/main/java/com/termux/app/TermuxService.java
Fixes https://github.com/termux/termux-app/issues/1032.
=> termux service: make sure that styling is always applied whenever session starts

app/src/main/java/com/termux/app/ExtraKeysView.java
Hi! This might help with https://github.com/termux/termux-app/issues/1125 .
=> Add function keys F1 to F12 as keyboard options

app/src/main/AndroidManifest.xml, app/src/main/java/com/termux/app/TermuxService.java
Should fix https://github.com/termux/termux-app/issues/1224.
=> Handle possible ActivityNotFoundException when requesting to disable battery optimizations

app/src/main/java/com/termux/app/TermuxActivity.java
Now it support complex URLs and some other schemes beyond just http/ftp.
=> improve url matching regex

app/src/main/java/com/termux/app/BackgroundJob.java
See https://github.com/termux/termux-app/issues/1286
=> Do not set LD_LIBRARY_PATH by default

.gitignore, app/build.gradle, app/src/main/cpp/Android.mk, app/src/main/cpp/termux-bootstrap-zip.S, app/src/main/cpp/termux-bootstrap.c, app/src/main/java/com/termux/app/BackgroundJob.java, app/src/main/java/com/termux/app/TermuxInstaller.java
I have created updated bootstraps for Android 5 and uploaded them here - https://bintray.com/termux/bootstrap/zips-legacy.
Now I guess we can create updated app for Android 5 devices.
=> [android-5] In-app bootstraps

app/src/main/java/com/termux/app/BackgroundJob.java
=> Properly set bootclasspath environment variable

app/src/main/AndroidManifest.xml
Closes #1259 
Tested on my device (Samsung S10)
Documentation here: https://developer.samsung.com/samsung-dex/modify-optimizing
=> Prevent kill by Samsung Dex on plug/unplug.

app/src/main/AndroidManifest.xml
Pull Request for Issue #1497 
added proposed line.
=> Add Log file to view intent #1497

app/src/main/java/com/termux/app/BackgroundJob.java
See https://gist.github.com/XVilka/8346728#true-color-detection
=> export COLORTERM=truecolor

app/src/main/res/drawable/ic_service_notification.xml
Updated notification icon to be in compliant with guidelines for material system icons (instead of Product icon guidelines)
Vector asset is imported in Android Studio 4.0 from SVG created in Figma. Outline shape is 100% replica of Launcher icon.
Reference issue #1619
=> update notification icon

terminal-emulator/src/main/java/com/termux/terminal/TerminalSession.java
See https://github.com/termux/termux-app/issues/1695.
=> terminal emulator: flush remaining process output data when terminating session

app/src/main/java/com/termux/app/TermuxActivity.java
allows the user to choose to open the link to install Termux:Styling via F-Droid too
=> Don't link directly to Google Play

app/src/main/java/com/termux/app/TermuxActivity.java
This is needed to allow https://github.com/termux/termux-api/pull/185 to work
* Sends a one time broadcast upon app launch to allow the optional TermuxAPI to perform the new checks in the mentioned PR. It has no coupling to the TermuxAPI, other than checking to see if there are any receivers that can listen to the broadcast action, which was needed to support Android Oreo.
=> Sends broadcast on app open to notify addon termux receivers

README.md
sorry if i didn't think of this but i think this is the updated one which discord ditches the "blurple" colorscheme 😅, more saturated
=> README: use the latest discord invite badge 

app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Added monochrome icon for Android 13 "Themed icons" support.
=> Added: Add monochrome icon

app/build.gradle
See https://github.com/robolectric/robolectric/releases/tag/robolectric-4.10.
=> Changed: Bump Robolectric to 4.10

README.md
README.md shows the latest version as v0.118.0 instead of v0.118.1 :P
=> Update latest version in README.md to v0.118.1

termux-shared/build.gradle
This should fix crash on A16 QPR1.
=> Update HiddenApiBypass to 6.1
